### PR TITLE
Make trace working when developing OData API in CPI Helper

### PR DESCRIPTION
**Pull request by SAPNickYang**
I have made two enhancement in CPI Helper.
1. Adding a copy icon in the end of each endpoint line in Info dialog. User can simply clicks the icon to cop, the endpoint URL to clipboard.
image

2. Making "Trace" function working in CPI when developing OData API.
image

### CODE REVIEW

**Comment by SAPNickYang** [comment]
This is for #13, adding "Deployed Version" to info menu.
Although it has already done in recent SAP CPI enhancement but very easy to add the information to CPI helper info menu.
image
image

**Comment by SAPNickYang** [comment]
Hi Dominic (@dbeck121 ),
Please check my two commits and see if it helps.
Thanks.

Regards,
Nick

**Comment by dbeck121** [comment]
Hey! Sorry I did not see your message. That is super great :) I will create a new Version :)

Thank you so much!

**Comment by dbeck121** [comment]
Feel free for more improvements :) If that is ok, I will add your name next to the  new Version release.

**Comment by SAPNickYang** [comment]
@dbeck121 Thanks for accepting my pull request. Actually the enhancement in the pull request are used quite frequently by myself and my colleagues and no problem to mention me in next release.
I am fortunate to do this based on your selfless contribution!
Planning to do some enhancement for "Tenant URLs".
Cheers.

**Pull request merged**
